{
    "name": "SendTxtMessage",
    "version": "1.0.0",
    "icon": "fab fa-phone",
    "category": "assistance",
    "author": "lazza",
    "maintainers": [
        "lazza"
    ],
    "desc": "Send a text message using ALice ",
    "aliceMinVersion": "1.0.0-b4",
    "systemRequirements": [],
    "pipRequirements": [],
    "conditions": {
        "lang": [
            "en"
        ],
        "online": true,
        "asrArbitraryCapture": false
    }
}
